### PR TITLE
DeleteUserIndicator route to write response

### PR DESCRIPTION
**Pull request by ZakarFin**
Deleting a user indicator didn't write any response when the operation is successful. Now writes the deleted indicator as JSON.

### CODE REVIEW

**Comment by jampukka** [comment]
Looks good to me. Could've made PARAM_INDICATOR_ID field final and the UserIndicatorService userIndicatorService member not-static in DeleteUserIndicatorHandler.

**Comment by ZakarFin** [comment]
Good points! I replaced the constant with another from ActionConstants class and removed static from service.

**Comment by jampukka** [comment]
Great. Now the only thing that stands out is that the Logger log is static final so I'd name it LOG instead and since the userIndicatorService is no longer static variable I'd swap the order in which the two fields appear in the class :)

**Comment by jampukka** [comment]
Thanks, it looks good to me.

**Pull request merged**
